### ISSUE TITLE
Slug field inside tab doesn't work since Nova 4.14.0

### ISSUE THREAD

**Issue by FreekVR** [eminiarts/nova-tabs#255]
Nova 4.14.0 included the following change:

```
Slug fields now return their preview from the server.
```

This change now yields an error given the following Tabs setup:

```php
Tabs::make('Content', [
  Tab::make(
      'TEST',
      [
          Text::make('Foo'),
          Slug::make('Sluggy')->from('Foo')
      ]
  )
])->showTitle(),
```

```
HTTP-404 /nova-api/undefined/field/sluggy/preview
```

It seems where it says "undefined" in the URL, should be the resource name, but that's somehow lost when the Slug field is included in a Tab.

**Comment by the-alichemist** [comment]
Fixed Bug: 
https://github.com/eminiarts/nova-tabs/pull/256

**Comment by FreekVR** [comment]
I'm afraid the original issue still persists on version 2.2.3;

`POST http://localhost/nova-api/undefined/field/slug:en/preview 404`

Where the URL now contains "undefined" should be the resource name normally.
